name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: cd ./Golang && go build -o allinone

    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
          files: allinone
          name: allinone_linux_amd64
          path: Golang
