name: IPTV-Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cross Compile
        run: |
          cd ./Golang
          GOOS=linux GOARCH=amd64 go build -o allinone_linux_amd64
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v3
        with:
          files: |
            allinone_linux_amd64
          name: allinone_linux_amd64
          path: Golang/

  linux_arm64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cross Compile
        run: |
          cd ./Golang
          GOOS=linux GOARCH=arm64 go build -o allinone_linux_arm64
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v3
        with:
          files: |
            allinone_linux_arm64
          name: allinone_linux_arm64
          path: Golang/
